### ISSUE TITLE
how to predict on Brats Validation case?

### ISSUE THREAD

**Issue by wangnanv5** [himashi92/VT-UNet#7]
First of all, thank you for your excellent work,i want to ask you a question,how to use this cood to predict a case.Brats Validation dataset only have four files,it don't have seg file, i want to use this code to predict on every validation case,looking forward to your reply.

**Comment by himashi92** [comment]
hello wangnav5,

You can use test.py script to predict cases for BraTS validation dataset. Since, there is no segmentation ground truth you have to modify https://github.com/himashi92/VT-UNet/blob/main/dataset/brats.py#L122 adding no_seg=True when calling Brats class and https://github.com/himashi92/VT-UNet/blob/main/utils.py#L239 generate_segmentations_monai method by removing ground truth related info. Saved predictions can be then submitted to the continuous evaluation portal https://www.synapse.org/#!Synapse:syn25829067/wiki/610863 

Kind regards,
Himashi

**Comment by wangnanv5** [comment]
Thanks for your approach, I have solved the problem.Thank!
